data:
  train_files: hiyouga/math12k@train
  val_files: hiyouga/math12k@test
  prompt_key: problem
  answer_key: answer
  image_key: images
  max_prompt_length: 6144
  max_response_length: 2048
  rollout_batch_size: 4
  shuffle: true
  seed: 1
  max_pixels: 4194304
  min_pixels: 262144
  is_gui: false

algorithm:
  adv_estimator: grpo_traj
  kl_coef: 0.0

worker:
  actor:
    global_batch_size: 128
    micro_batch_size_per_device_for_update: 1
    micro_batch_size_per_device_for_experience: 1
    max_grad_norm: 1.0
    entropy_coeff: 1.0e-3
    use_kl_loss: true
    kl_loss_coef: 1.0e-2
    kl_loss_type: low_var_kl
    padding_free: true
    ulysses_sequence_parallel_size: 1
    model:
      model_path: Qwen/Qwen2.5-7B-Instruct
      enable_gradient_checkpointing: true
      trust_remote_code: false
    optim:
      lr: 1.0e-6
      weight_decay: 1.0e-2
      lr_warmup_ratio: 0.0
    fsdp:
      enable_full_shard: true
      enable_cpu_offload: false
      enable_rank0_init: true
      torch_dtype: bfloat16
    offload:
      offload_params: false
      offload_optimizer: false

  rollout:
    temperature: 1.0
    n: 1
    gpu_memory_utilization: 0.5
    enforce_eager: false
    enable_chunked_prefill: false
    tensor_parallel_size: 2
    limit_images: 1
    env:
      bsize: 16
      n: 4
      avd_name: 'AndroidWorldAvd'
      android_avd_home: '/root/android/avd'
      emulator_path: '/root/android/emulator/emulator'
      adb_path: '/root/android/platform-tools/adb'
      max_steps: 15
      save_path: '/cq_1/share_1603164/user/yuchengshi/code/images'
      image_size: [1092, 2408]
      

  ref:
    offload:
      offload_params: false

  reward:
    reward_type: function
    compute_score: math

trainer:
  total_episodes: 10
  logger: ["console", "wandb"]
  project_name: gui_r1_yucheng_shi_dev
  experiment_name: qwen2_5_7b_math
  n_gpus_per_node: 8
  nnodes: 1
  val_freq: 50
  val_before_train: false
  val_only: false
  val_generations_to_log: 1
  save_freq: 50
  remove_previous_ckpt: false
  remove_ckpt_after_load: false
  save_checkpoint_path: '/gy_1/share_302625455/user/yuchengshi/qwenvl_verl_test' #/apdcephfs_gy2/share_302625455/user/kaixinma/gui_output/qwenvl_verl_test_hd
  load_checkpoint_path: null
  max_steps: 136
  val_steps: 3
